### ISSUE TITLE
failed to test16 on windows 2016

### ISSUE THREAD

**Issue by xiaoyafeng** [ingydotnet/Inline-Java#10]
t/16_subclass.t ........ Class t16subclass not found at C:\perl\data\.cpanm\work\1573707880.5336\Inline-Java-0.66\blib\l
ib/Inline/Java.pm line 613.
BEGIN failed--compilation aborted at t/16_subclass.t line 15, <GEN7> line 4.
t/16_subclass.t ........ Dubious, test returned 2 (wstat 512, 0x200)

perl -V
E:\software\WINDOWS.X64_193000_db_home\jdk\bin>perl -V
Summary of my perl5 (revision 5 version 30 subversion 0) configuration:

  Platform:
    osname=MSWin32
    osvers=10.0.17763.529
    archname=MSWin32-x64-multi-thread
    uname='Win32 strawberry-perl 5.30.0.1 #1 Thu May 23 12:20:46 2019 x64'
    config_args='undef'
    hint=recommended
    useposix=true
    d_sigaction=undef
    useithreads=define
    usemultiplicity=define
    use64bitint=define
    use64bitall=undef
    uselongdouble=undef
    usemymalloc=n
    default_inc_excludes_dot=define
    bincompat5005=undef
  Compiler:
    cc='gcc'
    ccflags =' -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_C
NTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields'
    optimize='-s -O2'
    cppflags='-DWIN32'
    ccversion=''
    gccversion='8.3.0'
    gccosandvers=''
    intsize=4
    longsize=4
    ptrsize=8
    doublesize=8
    byteorder=12345678
    doublekind=3
    d_longlong=define
    longlongsize=8
    d_longdbl=define
    longdblsize=16
    longdblkind=3
    ivtype='long long'
    ivsize=8
    nvtype='double'
    nvsize=8
    Off_t='long long'
    lseeksize=8
    alignbytes=8
    prototype=define
  Linker and Libraries:
    ld='g++.exe'
    ldflags ='-s -L"C:\perl\perl\lib\CORE" -L"C:\perl\c\lib"'
    libpth=C:\perl\c\lib C:\perl\c\x86_64-w64-mingw32\lib C:\perl\c\lib\gcc\x86_64-w64-mingw32\8.3.0
    libs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lnetapi
2 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    perllibs= -lmoldname -lkernel32 -luser32 -lgdi32 -lwinspool -lcomdlg32 -ladvapi32 -lshell32 -lole32 -loleaut32 -lne
api32 -luuid -lws2_32 -lmpr -lwinmm -lversion -lodbc32 -lodbccp32 -lcomctl32
    libc=
    so=dll
    useshrplib=true
    libperl=libperl530.a
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_win32.xs
    dlext=xs.dll
    d_dlsymun=undef
    ccdlflags=' '
    cccdlflags=' '
    lddlflags='-mdll -s -L"C:\perl\perl\lib\CORE" -L"C:\perl\c\lib"'

Characteristics of this binary (from libperl):
  Compile-time options:
    HAS_TIMES
    HAVE_INTERP_INTERN
    MULTIPLICITY
    PERLIO_LAYERS
    PERL_COPY_ON_WRITE
    PERL_DONT_CREATE_GVSV
    PERL_IMPLICIT_CONTEXT
    PERL_IMPLICIT_SYS
    PERL_MALLOC_WRAP
    PERL_OP_PARENT
    PERL_PRESERVE_IVUV
    USE_64_BIT_INT
    USE_ITHREADS
    USE_LARGE_FILES
    USE_LOCALE
    USE_LOCALE_COLLATE
    USE_LOCALE_CTYPE
    USE_LOCALE_NUMERIC
    USE_LOCALE_TIME
    USE_PERLIO
    USE_PERL_ATOF
  Built under MSWin32
  Compiled at May 23 2019 12:26:54
  @INC:
    C:/perl/perl/site/lib/MSWin32-x64-multi-thread
    C:/perl/perl/site/lib
    C:/perl/perl/vendor/lib
    C:/perl/perl/lib

java -version
E:\software\WINDOWS.X64_193000_db_home\jdk\bin>java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

Thanks in advance.

**Comment by zmughal** [comment]
Closed by <https://github.com/ingydotnet/Inline-Java/pull/11>.

**Comment by mohawk2** [comment]
Agreed - that's merged and will be released shortly. @xiaoyafeng Thank you for the report!
