### ISSUE TITLE
Fix debian build issues

### ISSUE THREAD

**Issue by mohawk2** [ingydotnet/Inline-Java#5]
This RT issue: https://rt.cpan.org/Ticket/Display.html?id=98683

links to this build log: https://buildd.debian.org/status/fetch.php?pkg=libinline-java-perl&arch=mips&ver=0.53-2&stamp=1405227323

**Comment by jonassmedegaard** [comment]
0.58 in Debian still fails: Overview is at https://tracker.debian.org/pkg/libinline-java-perl - build logs is in right pane of that page.

What more info is needed here?

**Comment by mohawk2** [comment]
@jonassmedegaard As far as I know, the distro should build on Debian now. I can't see any problems on the overview you linked above. If I'm missing them, can you tell me where to look?
