### ISSUE TITLE
J2SDK_BIN mismatch on darwin

### ISSUE THREAD

**Issue by TisonKun** [ingydotnet/Inline-Java#8]
https://github.com/ingydotnet/Inline-Java/blob/277ab80dac992ec4c6a63cb97e84a2e4af8b0298/lib/Inline/Java/Portable.pm#L245

when install java by SDKMAN!, the directory is `$JAVA_HOME/bin` not `$JAVA_HOME/Commands`, please add a candidate.

**Comment by mohawk2** [comment]
Could you make a pull request?

**Comment by TisonKun** [comment]
@mohawk2 sure. See #9
